language: bash

sudo: required
dist: trusty

os:
  - linux
  - osx

# Install dependencies
addons:
  apt:
    packages:
    - squashfs-tools

env:
  global:
    - ELIXIR_VERSION=1.4.0 ERLANG_VERSION=19.0
  matrix:
    - MIX_TARGET=rpi
    - MIX_TARGET=rpi2
    - MIX_TARGET=rpi3
    - MIX_TARGET=bbb

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      wget https://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/esl-erlang_$ERLANG_VERSION-1~ubuntu~trusty_amd64.deb;
      sudo dpkg -i esl-erlang_$ERLANG_VERSION-1~ubuntu~trusty_amd64.deb;
      wget https://github.com/fhunleth/fwup/releases/download/v0.13.0/fwup_0.13.0_amd64.deb;
      sudo dpkg -i fwup_0.13.0_amd64.deb;
    else
      brew update;
      brew install homebrew/versions/erlang-r19;
      brew install fwup;
      brew install squashfs;
      brew unlink coreutils;
      brew install coreutils;
    fi
  - wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VERSION/Precompiled.zip
  - unzip -d elixir Precompiled.zip

before_script:
  - export PATH=`pwd`/elixir/bin:$PATH

script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix archive.install https://github.com/nerves-project/archives/raw/master/nerves_bootstrap.ez --force
  - pushd blinky
  - mix do deps.get, firmware --verbosity=verbose
  - popd
  - pushd hello_gpio
  - mix do deps.get, firmware --verbosity=verbose
  - popd
  - pushd hello_gpio_input
  - mix do deps.get, firmware --verbosity=verbose
  - popd
  - pushd hello_leds
  - mix do deps.get, firmware --verbosity=verbose
  - popd
  - pushd hello_network
  - mix do deps.get, firmware --verbosity=verbose
  - popd
  - pushd hello_phoenix/apps/fw
  - mix do deps.get, firmware --verbosity=verbose
  - popd
  - pushd hello_wifi
  - mix do deps.get, firmware --verbosity=verbose
  - popd
  - pushd linkit
  - mix do deps.get, firmware --verbosity=verbose
  - popd
  - pushd neopixel
  - mix do deps.get, firmware --verbosity=verbose
  - popd
