version = 1

[[annotations]]
path = [
 "blinky/**",
 "minimal/**",
 "hello_erlang/**",
 "hello_gpio/**",
 "hello_lfe/**",
 "hello_live_view/**",
 "poncho_phoenix/**",
 "hello_scenic/**",
 "hello_snmp_agent/**",
 "hello_snmp_manager/**",
 "hello_sqlite/**",
 "hello_wifi/**",
 "hello_zig/**",
 "REUSE.toml",
 "scripts/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"
